### ISSUE TITLE
Add a "Festival" event type

### ISSUE THREAD

**Issue by kateabr** [VocaDB/community#155]
Add a new celebration-like category for events with free participation and no competitiveness/prizes; like "Character anniversary" but without focus on a particular character.

**Comment by CatgirlFrostmoon** [comment]
> Can you please make sure that it really makes sense to add a "Festival" event type, rather than having a "Festival" tag for events?

Immediately, I can find these from just a quick search:

https://vocadb.net/Es/310/kyokumei-touitsu-matsuri **(series)**
https://vocadb.net/E/4345/winter-shoegazer-festival-2010
https://vocadb.net/Es/357/lyrics-unification-festival **(series)**
https://vocadb.net/Es/307/vocaloid-a-cappella-festival **(series)**
https://vocadb.net/E/2506/post-voca-rock-festival-vol1
https://vocadb.net/E/1960/miku-festival
https://vocadb.net/E/1192/miku-festival-2
https://vocadb.net/E/4222/2022
https://vocadb.net/Es/322/neta-kyoku-toukousai **(series)**
https://vocadb.net/Es/74/anime-song-cover-festival **(series)**
https://vocadb.net/E/4115/artwork-unification-festival-m
https://vocadb.net/Es/341/cevio-upload-festival **(series)**
https://vocadb.net/E/1384/acfun-2017-spring-festival-gal

**Comment by ycanardeau** [comment]
@CatgirlFrostmoon Can you also please explain "why" you need this event type? It's not just a matter of a decent amount of festival-type events. An event type should have some logic in my opinion. If it's just for categorizing purposes only, I'd suggest using a tag. For example, if an artist has the "Vocaloid" artist type, then it also can have a base voicebank, and if a song has the "Cover" song type, then it can have an original version. But of course I'm not against adding a new event type if you can make proper guidelines for event types vs tags.

**Comment by CatgirlFrostmoon** [comment]
@ycanardeau My big reason for wanting it to be an actual type instead of a tag is that A: it doesn't actually match any of the types we already have, and B: that's causing issues. The various events above are categoried all over the place -- Unspecified, Other, and Contest have all been used. Other is the most accurate, but there's a very clear lack of consensus as to how to categorize these festivals. All of the examples you mentioned are things with actual matching types; there is no matching type for this event (excluding, perhaps, "Other"), leading to an array of categories for the same type of event.

**Comment by ycanardeau** [comment]
One more thing I want to confirm is that: is it very unlikely that other event types are added in the future? I remembered that there was some discussion about [adding a "Birthday" event type](https://github.com/VocaDB/community/issues/136) before. Currently, the [`EventCategory`](https://github.com/VocaDB/vocadb/blob/673227234dc22b39d2099b8743ab9d7d0f4c6ab7/VocaDbModel/Domain/ReleaseEvents/EventCategory.cs) enum is a [flags enum](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-6.0), and not a value enum for some reason, which means that the number of items is limited to 32 (I think we can safely convert it to a value enum though). Additionally, adding a new event type is super easy, but removing it later on is almost impossible.

**Comment by CatgirlFrostmoon** [comment]
I have no idea. The "anniversary" event type seems perfect for the birthday event as they're very similar overall -- _that's_ an area where the tags may help, or perhaps description can help differentiate birthdays and anniversaries and character days. I don't feel safe speaking on other potential event types, as who knows what will arise in the future.

**Comment by kateabr** [comment]
I don't think there will be any need to remove it: like CatgirlFrostmoon said, there already is a big number of such events, and there is going to be more of them. Speaking of adding more event types -- apart from the "Festival", all other types seem to be logical and covering most of the events that we currently have -- given that this is a strictly media-oriented database. At least, I can't think of another event type to add right from the top of my head.

> And are you planning to make a pull request?

I can try! Is adding a enum value all it takes?

**Comment by ycanardeau** [comment]
@kateabr @CatgirlFrostmoon The new "Festival" event type is available on the [beta site](https://beta.vocadb.net/).

**Comment by kateabr** [comment]
[Works](https://beta.vocadb.net/E/4115/artwork-unification-festival-m)!
