### ISSUE TITLE
kiite is different site from nicovideo but this code returns nicovideo URL on KiitePlaylistItem, is it okay?

### ISSUE THREAD

**Issue by daisukeokaoss** [VocaDB/community#182]
### Website
VocaDB

### Describe the bug

https://github.com/VocaDB/vocadb/blob/main/VocaDbModel/Service/SongImport/KiitePlaylistImporter.cs#L70

Kiite is different site from nicovideo but it returns nicovideo URL on KiitePlaylistItem, is it okay?

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable.

- [x] Users should limit themselves to three or less active issues and PRs at any one time.
- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**.
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by ycanardeau** [comment]
This is the correct behavior. `VideoUrl` is not for the playlist, but for the PV.
